### ISSUE TITLE
Was it fun copying me?

### ISSUE THREAD

**Issue by catzsec** [Chainski/ForceAdmin#1]

**Comment by Chainski** [comment]
I can delete the repo if you want but you this has nothing to do with yours.

**Comment by chainski** [comment]
If you wanted the credits bro you could just ask there's nothing hard in doing that.

![image](https://user-images.githubusercontent.com/96607632/215514853-e5758a08-469e-462d-8d46-69decd19ed22.png)

**Comment by ghost** [comment]
@catzsec  Was it fun copying us???  - bit ironic dont you think. we've been CaTZSeC for over 3 years. Hypocrite 
![image](https://user-images.githubusercontent.com/62566476/215697888-ced13356-8869-48c8-8068-9c966bc397d8.png)

**Comment by ghost** [comment]
even if you google catzsec we come up, be original - get off our name - your UAC is nothing special - leave @Chainski alone - he is just copying a project and even gave you credit - do we get credit. do our members of our team get credit?

**Comment by chainski** [comment]
> even if you google catzsec we come up, be original - get off our name - your UAC is nothing special - leave @Chainski alone - he is just copying a project and even gave you credit - do we get credit. do our members of our team get credit?

Good that you showed up as the name **Catzsec** is a team that's quite evident on [CTFTIME](https://ctftime.org/team/119166/) as I did a minor recon to get some information on how to deal with this case. If you may observe my repo a bit more carefully it's obviously the same concept implemented in 4 scripting languages but **not copied** as [catzsec's force admin](https://github.com/catzsec/ForceAdmin) is just C# based. Btw @catzsec I think it was fun to know you're the real copycat.

**Comment by ghost** [comment]
Just because we haven't participated in any CTF's since 2020, does not mean we are not active, and you can take our name @catzsec. I think you should rebrand asap!

**Comment by catzsec** [comment]
@ryku-1 I did not even know you guys existed - an inactive ctf team who has 1 search result ( under mine )

Here we have a copied repo, that has just been updated with more scripts copied from my other repo!

**Comment by msfcon5ol3** [comment]
> @ryku-1 I did not even know you guys existed - an inactive ctf team who has 1 search result ( under mine )
> 
> Here we have a copied repo, that has just been updated with more scripts copied from my other repo!

The guy already gave you credit what else do you want ?
And there's nothing special about your repositories as all of them are basically skidded imo so leave @Chainski alone , DAMN !!!
