### ISSUE TITLE
click

### ISSUE THREAD

**Issue by sec13b** [Chainski/ForceAdmin#3]
i test on windows server 2012 , i click 30min continuous :)))))))))))))))) with no result ::)))))))))))))))))))))))))))))

**Comment by chainski** [comment]
> i test on windows server 2012 , i click 30min continuous :)))))))))))))))) with no result ::)))))))))))))))))))))))))))))

 I really never tested it on windows server, however if you did , your results should be similar to the one in the P.O.C video shown the ```README``` unless you changed something in the code.

**Comment by sec13b** [comment]
ok, , thx 
have fun
